<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\ApplicantProfile;

class ApplicantProfileSeeder extends Seeder
{
    public function run(): void
    {
        $profiles = [
            // user_id 1 — Maria Santos
            [
                'user_id'                   => 1,
                'date_of_birth'             => '2005-06-12',
                'sex'                       => 'Female',
                'home_address'              => '123 Mabini St.',
                'city'                      => 'Baras',
                'province'                  => 'Rizal',
                'zip_code'                  => '1970',
                'mobile_number'             => '9171234567',
                'sms_opted_in'              => 0,
                'university_name'           => 'University of Rizal System',
                'university_address'        => 'Morong, Rizal',
                'university_email'          => 'maria.santos@urs.edu.ph',
                'course_program'            => 'BS Information Technology',
                'student_number'            => '2026-12345',
                'year_level'                => '1st Year',
                'semester'                  => '1st',
                'academic_year'             => '2026-2027',
                'gwa'                       => 1.25,
                'monthly_household_income'  => 12000.00,
                'num_dependents'            => 4,
                'is_breadwinner'            => 'Partial Contributor',
                'is_4ps'                    => 1,
                'father_employment_status'  => 'Tricycle Driver',
                'mother_employment_status'  => 'Unemployed',
                'profile_completed_at'      => '2026-01-08 00:00:00',
                'gwa_scale' => 'college',
            ],
            // user_id 2 — Juan Dela Cruz
            [
                'user_id'                   => 2,
                'date_of_birth'             => '2004-02-20',
                'sex'                       => 'Male',
                'home_address'              => '56 Sitio Wawa',
                'city'                      => 'Tanay',
                'province'                  => 'Rizal',
                'zip_code'                  => '1980',
                'mobile_number'             => '9181234567',
                'sms_opted_in'              => 0,
                'university_name'           => 'Polytechnic University of the Philippines',
                'university_address'        => 'Manila',
                'university_email'          => 'juan.dc@pup.edu.ph',
                'course_program'            => 'BS Civil Engineering',
                'student_number'            => '2026-54321',
                'year_level'                => '1st Year',
                'semester'                  => '1st',
                'academic_year'             => '2026-2027',
                'gwa'                       => 1.50,
                'monthly_household_income'  => 18000.00,
                'num_dependents'            => 5,
                'is_breadwinner'            => 'No',
                'is_4ps'                    => 0,
                'father_employment_status'  => 'Construction Worker',
                'mother_employment_status'  => 'Unemployed',
                'profile_completed_at'      => '2026-01-06 00:00:00',
                'gwa_scale' => 'college',
            ],
            // user_id 3 — Angela Reyes
            [
                'user_id'                   => 3,
                'date_of_birth'             => '2006-01-15',
                'sex'                       => 'Female',
                'home_address'              => '45 Sumulong Hwy',
                'city'                      => 'Caloocan',
                'province'                  => 'Metro Manila',
                'zip_code'                  => '1400',
                'mobile_number'             => '9191234567',
                'sms_opted_in'              => 0,
                'university_name'           => 'University of the Philippines Diliman',
                'university_address'        => 'Quezon City',
                'university_email'          => 'angela@upd.edu.ph',
                'course_program'            => 'BS Biology',
                'student_number'            => '2026-67890',
                'year_level'                => '1st Year',
                'semester'                  => '1st',
                'academic_year'             => '2026-2027',
                'gwa'                       => 1.25,
                'monthly_household_income'  => 10000.00,
                'num_dependents'            => 3,
                'is_breadwinner'            => 'No',
                'is_4ps'                    => 1,
                'father_employment_status'  => null,
                'mother_employment_status'  => 'Sewer',
                'profile_completed_at'      => '2026-01-07 00:00:00',
                'gwa_scale' => 'college',
            ],
            // user_id 4 — Kevin Cruz
            [
                'user_id'                   => 4,
                'date_of_birth'             => '2003-11-10',
                'sex'                       => 'Male',
                'home_address'              => '78 Ortigas Ave Ext',
                'city'                      => 'Cainta',
                'province'                  => 'Rizal',
                'zip_code'                  => '1900',
                'mobile_number'             => '9201234567',
                'sms_opted_in'              => 0,
                'university_name'           => 'STI College',
                'university_address'        => 'Ortigas-Cainta',
                'university_email'          => 'kevin@sti.edu.ph',
                'course_program'            => 'BS Computer Science',
                'student_number'            => '2026-11223',
                'year_level'                => '1st Year',
                'semester'                  => '1st',
                'academic_year'             => '2026-2027',
                'gwa'                       => 1.75,
                'monthly_household_income'  => 12000.00,
                'num_dependents'            => 2,
                'is_breadwinner'            => 'Partial Contributor',
                'is_4ps'                    => 0,
                'father_employment_status'  => 'Office Staff',
                'mother_employment_status'  => 'Unemployed',
                'profile_completed_at'      => '2026-01-03 00:00:00',
                'gwa_scale' => 'college',
            ],
            // user_id 5 — Liz Mendoza
            [
                'user_id'                   => 5,
                'date_of_birth'             => '2005-09-08',
                'sex'                       => 'Female',
                'home_address'              => 'Brgy. San Guillermo',
                'city'                      => 'Manila',
                'province'                  => 'Metro Manila',
                'zip_code'                  => '1960',
                'mobile_number'             => '9211234567',
                'sms_opted_in'              => 0,
                'university_name'           => 'National Teachers College',
                'university_address'        => 'Manila',
                'university_email'          => 'lm@ntc.edu.ph',
                'course_program'            => 'BS Secondary Education',
                'student_number'            => '2026-33445',
                'year_level'                => '1st Year',
                'semester'                  => '1st',
                'academic_year'             => '2026-2027',
                'gwa'                       => 1.50,
                'monthly_household_income'  => 15000.00,
                'num_dependents'            => 6,
                'is_breadwinner'            => 'Yes',
                'is_4ps'                    => 1,
                'father_employment_status'  => null,
                'mother_employment_status'  => 'Street Vendor',
                'profile_completed_at'      => '2026-01-05 00:00:00',
                'gwa_scale' => 'college',
            ],
            // user_id 6 — Mark Villanueva
            [
                'user_id'                   => 6,
                'date_of_birth'             => '2004-04-25',
                'sex'                       => 'Male',
                'home_address'              => '23 Marulas',
                'city'                      => 'Valenzuela',
                'province'                  => 'Metro Manila',
                'zip_code'                  => '1140',
                'mobile_number'             => '9221234567',
                'sms_opted_in'              => 0,
                'university_name'           => 'Technological Institute of the Philippines',
                'university_address'        => 'Manila',
                'university_email'          => 'mark.v@tip.edu.ph',
                'course_program'            => 'BS Mechanical Engineering',
                'student_number'            => '2026-99887',
                'year_level'                => '1st Year',
                'semester'                  => '1st',
                'academic_year'             => '2026-2027',
                'gwa'                       => 1.75,
                'monthly_household_income'  => 12500.00,
                'num_dependents'            => 3,
                'is_breadwinner'            => 'No',
                'is_4ps'                    => 0,
                'father_employment_status'  => 'Factory Worker',
                'mother_employment_status'  => 'Deceased',
                'profile_completed_at'      => '2026-01-12 00:00:00',
                'gwa_scale' => 'college',
            ],
            // user_id 7 — Nicole Garcia
            [
                'user_id'                   => 7,
                'date_of_birth'             => '2006-07-30',
                'sex'                       => 'Female',
                'home_address'              => 'Purok 3, Brgy. Basak',
                'city'                      => 'Lapu-Lapu',
                'province'                  => 'Cebu',
                'zip_code'                  => '6015',
                'mobile_number'             => '9231234567',
                'sms_opted_in'              => 0,
                'university_name'           => 'University of San Carlos',
                'university_address'        => 'Cebu',
                'university_email'          => 'nicole.garcia@usc.edu.ph',
                'course_program'            => 'BS Information Technology',
                'student_number'            => '2026-55667',
                'year_level'                => '1st Year',
                'semester'                  => '1st',
                'academic_year'             => '2026-2027',
                'gwa'                       => 2.00,
                'monthly_household_income'  => 11000.00,
                'num_dependents'            => 5,
                'is_breadwinner'            => 'Partial Contributor',
                'is_4ps'                    => 1,
                'father_employment_status'  => 'Fisherman',
                'mother_employment_status'  => 'Vendor',
                'profile_completed_at'      => '2026-01-04 00:00:00',
                'gwa_scale' => 'college',
            ],
            // user_id 8 — Joshua Lim
            [
                'user_id'                   => 8,
                'date_of_birth'             => '2003-03-14',
                'sex'                       => 'Male',
                'home_address'              => '45 J.P. Laurel Ave',
                'city'                      => 'Davao',
                'province'                  => 'Davao Del Sur',
                'zip_code'                  => '8000',
                'mobile_number'             => '9241234567',
                'sms_opted_in'              => 0,
                'university_name'           => 'Ateneo de Davao University',
                'university_address'        => 'Davao',
                'university_email'          => 'jlim@addu.edu.ph',
                'course_program'            => 'BS Accountancy',
                'student_number'            => '2026-22334',
                'year_level'                => '1st Year',
                'semester'                  => '1st',
                'academic_year'             => '2026-2027',
                'gwa'                       => 1.75,
                'monthly_household_income'  => 35000.00,
                'num_dependents'            => 3,
                'is_breadwinner'            => 'No',
                'is_4ps'                    => 0,
                'father_employment_status'  => 'Small Business Owner',
                'mother_employment_status'  => 'Small Business Owner',
                'profile_completed_at'      => '2026-01-09 00:00:00',
                'gwa_scale' => 'college',
            ],
            // user_id 9 — Fatima Hassan
            [
                'user_id'                   => 9,
                'date_of_birth'             => '2005-12-01',
                'sex'                       => 'Female',
                'home_address'              => 'Zone 2, Brgy. Poblacion',
                'city'                      => 'Marawi',
                'province'                  => 'Lanao Del Sur',
                'zip_code'                  => '9700',
                'mobile_number'             => '9251234567',
                'sms_opted_in'              => 0,
                'university_name'           => 'Mindanao State University',
                'university_address'        => 'Marawi',
                'university_email'          => 'fatima.hassan@msu.edu.ph',
                'course_program'            => 'BS Psychology',
                'student_number'            => '2026-66778',
                'year_level'                => '1st Year',
                'semester'                  => '1st',
                'academic_year'             => '2026-2027',
                'gwa'                       => 1.50,
                'monthly_household_income'  => 14000.00,
                'num_dependents'            => 6,
                'is_breadwinner'            => 'Partial Contributor',
                'is_4ps'                    => 0,
                'father_employment_status'  => 'Farmer',
                'mother_employment_status'  => 'Unemployed',
                'profile_completed_at'      => '2026-01-02 00:00:00',
                'gwa_scale' => 'college',
            ],
            // user_id 10 — Alex Rivera
            [
                'user_id'                   => 10,
                'date_of_birth'             => '2004-08-18',
                'sex'                       => 'Male',
                'home_address'              => '12 Burgos St.',
                'city'                      => 'Baguio',
                'province'                  => 'Benguet',
                'zip_code'                  => '2600',
                'mobile_number'             => '9261234567',
                'sms_opted_in'              => 0,
                'university_name'           => 'University of the Cordilleras',
                'university_address'        => 'Baguio',
                'university_email'          => 'alex.rivera@uc-bcf.edu.ph',
                'course_program'            => 'BS Electronics Engineering',
                'student_number'            => '2026-88990',
                'year_level'                => '1st Year',
                'semester'                  => '1st',
                'academic_year'             => '2026-2027',
                'gwa'                       => 1.25,
                'monthly_household_income'  => 16000.00,
                'num_dependents'            => 4,
                'is_breadwinner'            => 'No',
                'is_4ps'                    => 1,
                'father_employment_status'  => 'Market Vendor',
                'mother_employment_status'  => 'Market Vendor',
                'profile_completed_at'      => '2026-01-01 00:00:00',
                'gwa_scale' => 'college',
            ],

            // user_id 21 — Sofia Aguilar
            [
                'user_id'                   => 21,
                'date_of_birth'             => '2007-03-14',
                'sex'                       => 'Female',
                'home_address'              => '88 Maharlika St.',
                'city'                      => 'Lipa',
                'province'                  => 'Batangas',
                'zip_code'                  => '4217',
                'mobile_number'             => '9271234567',
                'sms_opted_in'              => 0,
                'university_name'           => 'Batangas State University',
                'university_address'        => 'Batangas City, Batangas',
                'university_email'          => 'sofia.aguilar@g.batstate-u.edu.ph',
                'course_program'            => 'BS Nursing',
                'student_number'            => '2026-10011',
                'year_level'                => '1st Year',
                'semester'                  => '1st',
                'academic_year'             => '2026-2027',
                'gwa'                       => 94.00,
                'monthly_household_income'  => 14000.00,
                'num_dependents'            => 4,
                'is_breadwinner'            => 'No',
                'is_4ps'                    => 0,
                'father_employment_status'  => 'Jeepney Driver',
                'mother_employment_status'  => 'Unemployed',
                'profile_completed_at'      => null,
                'gwa_scale'                 => 'shs',
            ],
            // user_id 22 — Miguel Torres
            [
                'user_id'                   => 22,
                'date_of_birth'             => '2007-08-22',
                'sex'                       => 'Male',
                'home_address'              => '12 Sampaguita Lane',
                'city'                      => 'San Juan',
                'province'                  => 'Metro Manila',
                'zip_code'                  => '1500',
                'mobile_number'             => '9281234567',
                'sms_opted_in'              => 0,
                'university_name'           => 'San Juan De Letran College',
                'university_address'        => 'Intramuros, Manila',
                'university_email'          => 'miguel.torres@letran.edu.ph',
                'course_program'            => 'BS Architecture',
                'student_number'            => '2026-10012',
                'year_level'                => '1st Year',
                'semester'                  => '1st',
                'academic_year'             => '2026-2027',
                'gwa'                       => 89.00,
                'monthly_household_income'  => 22000.00,
                'num_dependents'            => 3,
                'is_breadwinner'            => 'No',
                'is_4ps'                    => 0,
                'father_employment_status'  => 'Construction Worker',
                'mother_employment_status'  => 'Street Vendor',
                'profile_completed_at'      => null,
                'gwa_scale'                 => 'shs',
            ],
            // user_id 23 — Hannah Pascual
            [
                'user_id'                   => 23,
                'date_of_birth'             => '2006-11-05',
                'sex'                       => 'Female',
                'home_address'              => 'Zone 4 Brgy. Sta. Cruz',
                'city'                      => 'Malolos',
                'province'                  => 'Bulacan',
                'zip_code'                  => '3000',
                'mobile_number'             => '9291234567',
                'sms_opted_in'              => 1,
                'university_name'           => 'Bulacan State University',
                'university_address'        => 'Malolos, Bulacan',
                'university_email'          => 'hannah.pascual@bulsu.edu.ph',
                'course_program'            => 'BS Elementary Education',
                'student_number'            => '2026-10013',
                'year_level'                => '1st Year',
                'semester'                  => '1st',
                'academic_year'             => '2026-2027',
                'gwa'                       => 91.00,
                'monthly_household_income'  => 11500.00,
                'num_dependents'            => 5,
                'is_breadwinner'            => 'Partial Contributor',
                'is_4ps'                    => 1,
                'father_employment_status'  => 'Farmer',
                'mother_employment_status'  => 'Unemployed',
                'profile_completed_at'      => null,
                'gwa_scale'                 => 'shs',
            ],
            // user_id 24 — Rainier Domingo
            [
                'user_id'                   => 24,
                'date_of_birth'             => '2007-01-30',
                'sex'                       => 'Male',
                'home_address'              => '34 Rizal Ave. Ext.',
                'city'                      => 'Caloocan',
                'province'                  => 'Metro Manila',
                'zip_code'                  => '1400',
                'mobile_number'             => '9301234567',
                'sms_opted_in'              => 0,
                'university_name'           => 'Polytechnic University of the Philippines',
                'university_address'        => 'Sta. Mesa, Manila',
                'university_email'          => 'rainier.domingo@pup.edu.ph',
                'course_program'            => 'BS Electrical Engineering',
                'student_number'            => '2026-10014',
                'year_level'                => '1st Year',
                'semester'                  => '1st',
                'academic_year'             => '2026-2027',
                'gwa'                       => 86.00,
                'monthly_household_income'  => 17000.00,
                'num_dependents'            => 4,
                'is_breadwinner'            => 'No',
                'is_4ps'                    => 0,
                'father_employment_status'  => 'Security Guard',
                'mother_employment_status'  => 'Unemployed',
                'profile_completed_at'      => null,
                'gwa_scale'                 => 'shs',
            ],
            // user_id 25 — Camille Navarro
            [
                'user_id'                   => 25,
                'date_of_birth'             => '2006-09-17',
                'sex'                       => 'Female',
                'home_address'              => 'Purok 5 Brgy. Labangon',
                'city'                      => 'Cebu City',
                'province'                  => 'Cebu',
                'zip_code'                  => '6000',
                'mobile_number'             => '9311234567',
                'sms_opted_in'              => 1,
                'university_name'           => 'University of San Carlos',
                'university_address'        => 'Cebu City, Cebu',
                'university_email'          => 'camille.navarro@usc.edu.ph',
                'course_program'            => 'BS Biology',
                'student_number'            => '2026-10015',
                'year_level'                => '1st Year',
                'semester'                  => '1st',
                'academic_year'             => '2026-2027',
                'gwa'                       => 95.00,
                'monthly_household_income'  => 13000.00,
                'num_dependents'            => 6,
                'is_breadwinner'            => 'Partial Contributor',
                'is_4ps'                    => 1,
                'father_employment_status'  => 'Fisherman',
                'mother_employment_status'  => 'Deceased',
                'profile_completed_at'      => null,
                'gwa_scale'                 => 'shs',
            ],
        ];

        foreach ($profiles as $profile) {
            ApplicantProfile::create($profile);
        }
    }
}
