<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Application;

class ApplicationSeeder extends Seeder
{
    public function run(): void
    {
        $applications = [
            // ── MARIA SANTOS (applicant_id 1) ─────────────────
            [
                'reference_code'  => 'GD-2026-00001',
                'applicant_id'    => 1,
                'scholarship_id'  => 1,
                'status'          => 'approved',
                'stage'           => 'decided',
                'ai_match_score'  => 92.50,
                'conflict_flag'   => 0,
                'submitted_at'    => '2026-01-10 00:00:00',
                'decided_at'      => '2026-02-15 00:00:00',
            ],
            [
                'reference_code'  => 'SF-2026-00001',
                'applicant_id'    => 1,
                'scholarship_id'  => 7,
                'status'          => 'under_review',
                'stage'           => 'scoring',
                'ai_match_score'  => 88.00,
                'conflict_flag'   => 0,
                'submitted_at'    => '2026-01-12 00:00:00',
                'decided_at'      => null,
            ],
            [
                'reference_code'  => 'CM-2026-00001',
                'applicant_id'    => 1,
                'scholarship_id'  => 16,
                'status'          => 'pending',
                'stage'           => 'submitted',
                'ai_match_score'  => 85.00,
                'conflict_flag'   => 0,
                'submitted_at'    => '2026-02-01 00:00:00',
                'decided_at'      => null,
            ],

            // ── JUAN DELA CRUZ (applicant_id 2) ───────────────
            [
                'reference_code'  => 'LK-2026-00001',
                'applicant_id'    => 2,
                'scholarship_id'  => 4,
                'status'          => 'rejected',
                'stage'           => 'decided',
                'ai_match_score'  => 70.00,
                'conflict_flag'   => 0,
                'submitted_at'    => '2026-01-08 00:00:00',
                'decided_at'      => '2026-02-10 00:00:00',
            ],
            [
                'reference_code'  => 'US-2026-00001',
                'applicant_id'    => 2,
                'scholarship_id'  => 11,
                'status'          => 'under_review',
                'stage'           => 'doc_review',
                'ai_match_score'  => 74.00,
                'conflict_flag'   => 0,
                'submitted_at'    => '2026-01-20 00:00:00',
                'decided_at'      => null,
            ],
            [
                'reference_code'  => 'AP-2026-00001',
                'applicant_id'    => 2,
                'scholarship_id'  => 15,
                'status'          => 'pending',
                'stage'           => 'submitted',
                'ai_match_score'  => 72.00,
                'conflict_flag'   => 0,
                'submitted_at'    => '2026-02-05 00:00:00',
                'decided_at'      => null,
            ],

            // ── ANGELA REYES (applicant_id 3) ─────────────────
            [
                'reference_code'  => 'AE-2026-00001',
                'applicant_id'    => 3,
                'scholarship_id'  => 2,
                'status'          => 'approved',
                'stage'           => 'decided',
                'ai_match_score'  => 91.00,
                'conflict_flag'   => 0,
                'submitted_at'    => '2026-01-09 00:00:00',
                'decided_at'      => '2026-02-12 00:00:00',
            ],
            [
                'reference_code'  => 'SG-2026-00001',
                'applicant_id'    => 3,
                'scholarship_id'  => 3,
                'status'          => 'under_review',
                'stage'           => 'scoring',
                'ai_match_score'  => 89.50,
                'conflict_flag'   => 0,
                'submitted_at'    => '2026-01-15 00:00:00',
                'decided_at'      => null,
            ],
            [
                'reference_code'  => 'AY-2026-00001',
                'applicant_id'    => 3,
                'scholarship_id'  => 18,
                'status'          => 'pending',
                'stage'           => 'submitted',
                'ai_match_score'  => 86.00,
                'conflict_flag'   => 0,
                'submitted_at'    => '2026-02-03 00:00:00',
                'decided_at'      => null,
            ],

            // ── KEVIN CRUZ (applicant_id 4) ───────────────────
            [
                'reference_code'  => 'SF-2026-00002',
                'applicant_id'    => 4,
                'scholarship_id'  => 7,
                'status'          => 'under_review',
                'stage'           => 'doc_review',
                'ai_match_score'  => 80.00,
                'conflict_flag'   => 0,
                'submitted_at'    => '2026-01-18 00:00:00',
                'decided_at'      => null,
            ],
            [
                'reference_code'  => 'EP-2026-00001',
                'applicant_id'    => 4,
                'scholarship_id'  => 6,
                'status'          => 'rejected',
                'stage'           => 'decided',
                'ai_match_score'  => 65.00,
                'conflict_flag'   => 0,
                'submitted_at'    => '2026-01-05 00:00:00',
                'decided_at'      => '2026-02-08 00:00:00',
            ],
            [
                'reference_code'  => 'PN-2026-00001',
                'applicant_id'    => 4,
                'scholarship_id'  => 19,
                'status'          => 'pending',
                'stage'           => 'submitted',
                'ai_match_score'  => 78.00,
                'conflict_flag'   => 0,
                'submitted_at'    => '2026-02-07 00:00:00',
                'decided_at'      => null,
            ],

            // ── LIZ MENDOZA (applicant_id 5) ──────────────────
            [
                'reference_code'  => 'BP-2026-00001',
                'applicant_id'    => 5,
                'scholarship_id'  => 5,
                'status'          => 'approved',
                'stage'           => 'decided',
                'ai_match_score'  => 87.00,
                'conflict_flag'   => 0,
                'submitted_at'    => '2026-01-07 00:00:00',
                'decided_at'      => '2026-02-14 00:00:00',
            ],
            [
                'reference_code'  => 'LY-2026-00001',
                'applicant_id'    => 5,
                'scholarship_id'  => 12,
                'status'          => 'under_review',
                'stage'           => 'scoring',
                'ai_match_score'  => 83.50,
                'conflict_flag'   => 0,
                'submitted_at'    => '2026-01-22 00:00:00',
                'decided_at'      => null,
            ],
            [
                'reference_code'  => 'PG-2026-00001',
                'applicant_id'    => 5,
                'scholarship_id'  => 13,
                'status'          => 'pending',
                'stage'           => 'submitted',
                'ai_match_score'  => 81.00,
                'conflict_flag'   => 0,
                'submitted_at'    => '2026-02-02 00:00:00',
                'decided_at'      => null,
            ],

            // ── MARK VILLANUEVA (applicant_id 6) ──────────────
            [
                'reference_code'  => 'BH-2026-00001',
                'applicant_id'    => 6,
                'scholarship_id'  => 8,
                'status'          => 'revision',
                'stage'           => 'doc_review',
                'ai_match_score'  => 79.00,
                'conflict_flag'   => 0,
                'submitted_at'    => '2026-01-14 00:00:00',
                'decided_at'      => null,
            ],
            [
                'reference_code'  => 'SF-2026-00003',
                'applicant_id'    => 6,
                'scholarship_id'  => 7,
                'status'          => 'under_review',
                'stage'           => 'scoring',
                'ai_match_score'  => 82.00,
                'conflict_flag'   => 0,
                'submitted_at'    => '2026-01-19 00:00:00',
                'decided_at'      => null,
            ],
            [
                'reference_code'  => 'SB-2026-00001',
                'applicant_id'    => 6,
                'scholarship_id'  => 20,
                'status'          => 'pending',
                'stage'           => 'submitted',
                'ai_match_score'  => 77.00,
                'conflict_flag'   => 0,
                'submitted_at'    => '2026-02-06 00:00:00',
                'decided_at'      => null,
            ],

            // ── NICOLE GARCIA (applicant_id 7) ────────────────
            [
                'reference_code'  => 'LK-2026-00002',
                'applicant_id'    => 7,
                'scholarship_id'  => 4,
                'status'          => 'approved',
                'stage'           => 'decided',
                'ai_match_score'  => 76.00,
                'conflict_flag'   => 0,
                'submitted_at'    => '2026-01-06 00:00:00',
                'decided_at'      => '2026-02-11 00:00:00',
            ],
            [
                'reference_code'  => 'PG-2026-00002',
                'applicant_id'    => 7,
                'scholarship_id'  => 13,
                'status'          => 'under_review',
                'stage'           => 'doc_review',
                'ai_match_score'  => 74.50,
                'conflict_flag'   => 0,
                'submitted_at'    => '2026-01-23 00:00:00',
                'decided_at'      => null,
            ],
            [
                'reference_code'  => 'AP-2026-00002',
                'applicant_id'    => 7,
                'scholarship_id'  => 15,
                'status'          => 'pending',
                'stage'           => 'submitted',
                'ai_match_score'  => 73.00,
                'conflict_flag'   => 0,
                'submitted_at'    => '2026-02-04 00:00:00',
                'decided_at'      => null,
            ],

            // ── JOSHUA LIM (applicant_id 8) ───────────────────
            [
                'reference_code'  => 'EX-2026-00001',
                'applicant_id'    => 8,
                'scholarship_id'  => 9,
                'status'          => 'under_review',
                'stage'           => 'scoring',
                'ai_match_score'  => 84.00,
                'conflict_flag'   => 0,
                'submitted_at'    => '2026-01-16 00:00:00',
                'decided_at'      => null,
            ],
            [
                'reference_code'  => 'CS-2026-00001',
                'applicant_id'    => 8,
                'scholarship_id'  => 14,
                'status'          => 'approved',
                'stage'           => 'decided',
                'ai_match_score'  => 86.50,
                'conflict_flag'   => 0,
                'submitted_at'    => '2026-01-11 00:00:00',
                'decided_at'      => '2026-02-16 00:00:00',
            ],
            [
                'reference_code'  => 'PN-2026-00002',
                'applicant_id'    => 8,
                'scholarship_id'  => 19,
                'status'          => 'pending',
                'stage'           => 'submitted',
                'ai_match_score'  => 80.00,
                'conflict_flag'   => 0,
                'submitted_at'    => '2026-03-08 00:00:00',
                'decided_at'      => null,
            ],

            // ── FATIMA HASSAN (applicant_id 9) ────────────────
            [
                'reference_code'  => 'BP-2026-00002',
                'applicant_id'    => 9,
                'scholarship_id'  => 5,
                'status'          => 'rejected',
                'stage'           => 'decided',
                'ai_match_score'  => 69.00,
                'conflict_flag'   => 0,
                'submitted_at'    => '2026-01-04 00:00:00',
                'decided_at'      => '2026-02-09 00:00:00',
            ],
            [
                'reference_code'  => 'BS-2026-00001',
                'applicant_id'    => 9,
                'scholarship_id'  => 10,
                'status'          => 'under_review',
                'stage'           => 'doc_review',
                'ai_match_score'  => 71.50,
                'conflict_flag'   => 0,
                'submitted_at'    => '2026-02-21 00:00:00',
                'decided_at'      => null,
            ],
            [
                'reference_code'  => 'PG-2026-00003',
                'applicant_id'    => 9,
                'scholarship_id'  => 13,
                'status'          => 'pending',
                'stage'           => 'submitted',
                'ai_match_score'  => 75.00,
                'conflict_flag'   => 0,
                'submitted_at'    => '2026-02-09 00:00:00',
                'decided_at'      => null,
            ],

            // ── ALEX RIVERA (applicant_id 10) ─────────────────
            [
                'reference_code'  => 'GD-2026-00002',
                'applicant_id'    => 10,
                'scholarship_id'  => 1,
                'status'          => 'approved',
                'stage'           => 'decided',
                'ai_match_score'  => 93.00,
                'conflict_flag'   => 0,
                'submitted_at'    => '2026-01-03 00:00:00',
                'decided_at'      => '2026-02-13 00:00:00',
            ],
            [
                'reference_code'  => 'SF-2026-00004',
                'applicant_id'    => 10,
                'scholarship_id'  => 7,
                'status'          => 'under_review',
                'stage'           => 'scoring',
                'ai_match_score'  => 90.00,
                'conflict_flag'   => 0,
                'submitted_at'    => '2026-02-17 00:00:00',
                'decided_at'      => null,
            ],
            [
                'reference_code'  => 'CM-2026-00002',
                'applicant_id'    => 10,
                'scholarship_id'  => 16,
                'status'          => 'pending',
                'stage'           => 'submitted',
                'ai_match_score'  => 88.00,
                'conflict_flag'   => 0,
                'submitted_at'    => '2026-02-10 00:00:00',
                'decided_at'      => null,
            ],
        ];

        foreach ($applications as $application) {
            Application::create($application);
        }
    }
}
