<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Scholarship;

class ScholarshipSeeder extends Seeder
{
    public function run(): void
    {
        $scholarships = [
            // 1 — Gabay Dunong Scholarship
            [
                'provider_name'     => 'Gabay Foundation PH',
                'created_by'        => 27,
                'name'              => 'Gabay Dunong Scholarship',
                'tagline'           => 'Guiding Every Filipino Towards a Brighter Tomorrow.',
                'description'       => 'The Gabay Dunong Scholarship by Gabay Foundation PH is a community-centered program dedicated to supporting deserving Filipino students from low-income households in pursuing their education. Designed to ease financial burdens while nurturing academic excellence and character, the scholarship provides comprehensive assistance—including tuition support, stipends, and learning resources.' . "\n\n" . 'More than financial aid, Gabay Dunong serves as a guiding force, empowering scholars to stay committed to their studies, uphold strong values, and actively engage in opportunities that foster growth. By investing in education, the program aims to uplift individuals, strengthen communities, and build a brighter, more inclusive future for the next generation.',
                'gpa_requirement'   => 1.75,
                'income_bracket'    => '≤ ₱250,000/yr',
                'slots'             => 50,
                'eligibility'       => "Filipino citizen currently enrolled in a recognized school\n\nMust be from an indigent or low-income household\n\nMust not be a recipient of any other scholarship program\n\nMust have no failing grades in the previous semester\n\nMust demonstrate good moral character certified by the school\n\nMust be a resident of the covered barangay or municipality",
                'benefits'          => "Full tuition assistance up to ₱15,000 annually\n\nAnnual stipend of ₱10,000 released quarterly\n\nSchool supplies and materials allowance\n\nBook allowance of ₱2,000 per semester\n\nCertificate of recognition upon completion of each school year\n\nPriority access to partner institution learning sessions",
                'requirements'      => "Barangay Certificate of Indigency\n\nIncome Tax Return (ITR) or Certificate of Non-Filing\n\nLatest Report Card (Form 138) or Transcript of Records\n\nCertificate of Good Moral Character\n\n2x2 ID Photo (2 copies)\n\nBirth Certificate (PSA copy)\n\nValid government-issued ID of parent/guardian\n\nProof of Enrollment / Certificate of Registration",
                'open_date'         => '2025-12-01',
                'deadline'          => '2026-02-28',
                'status'            => 'closed',
                'blind_screening'   => 0,
                'weight_gpa'        => 50,
                'weight_income'     => 50,
                'tags'              => null,
                'ai_match_enabled'  => 1,
                'gcal_event_id'     => null,
                'contact_email'     => 'scholarships@gabayfoundationph.org',
                'website'           => 'https://www.gabayfoundationph.org',
                'address'           => '12 Roxas Boulevard, Ermita, Manila, Metro Manila 1000',
                'benefit_snippet_1' => 'Full tuition assistance up to ₱15,000/yr',
                'benefit_snippet_2' => 'Annual stipend of ₱10,000 released quarterly',
                'org_logo'          => 'storage/app/logos/gabay_foundation_ph.png',
                'posted_at'         => '2025-11-15 00:00:00',
            ],
            // 2 — AccessED College Support Grant
            [
                'provider_name'     => 'AccessED Philippines Foundation',
                'created_by'        => 27,
                'name'              => 'AccessED College Support Grant',
                'tagline'           => 'Access to Education — No Exceptions',
                'description'       => 'The AccessED College Support Grant by AccessED Philippines Foundation is a student-focused initiative that empowers academically capable yet financially challenged college students to pursue higher education. It is designed to bridge the gap between potential and opportunity by providing essential financial and academic support.' . "\n\n" . 'Beyond tuition assistance and monthly stipends, the program fosters continuous growth through mentoring, tutoring, and academic resources. It aims to equip scholars with the tools they need not only to succeed in school but also to thrive in their future careers and communities.',
                'gpa_requirement'   => 1.50,
                'income_bracket'    => 'Below ₱240,000 annually',
                'slots'             => 100,
                'eligibility'       => "Filipino citizen enrolled in a college degree program\n\nMust have no failing grades in the previous academic year\n\nMust not be a recipient of any other scholarship\n\nMust demonstrate financial need through submitted documents\n\nMust maintain GPA of 1.50 or higher throughout the program\n\nMust be enrolled in a recognized college or university",
                'benefits'          => "Tuition fee subsidy up to ₱20,000 per semester\n\nMonthly stipend of ₱2,000 released every month\n\nBook allowance per semester\n\nSchool supplies kit provided at the start of each school year\n\nAccess to academic mentoring and tutoring sessions\n\nCertificate of scholarship upon each successful school year",
                'requirements'      => "Barangay Certificate of Residency\n\nCertificate of Non-Filing or ITR\n\nTranscript of Records / Form 138\n\nCertificate of Good Moral Character\n\nPSA Birth Certificate\n\n2x2 ID Photo (2 copies)\n\nProof of Enrollment\n\nValid ID of parent/guardian",
                'open_date'         => '2025-12-01',
                'deadline'          => '2026-02-28',
                'status'            => 'closed',
                'blind_screening'   => 0,
                'weight_gpa'        => 50,
                'weight_income'     => 50,
                'tags'              => null,
                'ai_match_enabled'  => 1,
                'gcal_event_id'     => null,
                'contact_email'     => 'grants@accessedph.org',
                'website'           => 'https://www.accessedph.org',
                'address'           => '4F Strata 100 Bldg, F. Ortigas Jr. Road, Ortigas Center, Pasig City 1605',
                'benefit_snippet_1' => 'Tuition fee subsidy up to ₱20,000/semester',
                'benefit_snippet_2' => 'Monthly stipend of ₱2,000 every month',
                'org_logo'          => 'storage/app/logos/accesed_philippines_foundation.png',
                'posted_at'         => '2025-11-18 00:00:00',
            ],
            // 3 — Summit Scholars Grant
            [
                'provider_name'     => 'Summit Educational Support Foundation',
                'created_by'        => 27,
                'name'              => 'Summit Scholars Grant',
                'tagline'           => 'Elevating Filipino Scholars to New Heights',
                'description'       => 'The Summit Scholars Grant by Summit Educational Support Foundation is a forward-looking program that invests in the next generation of STEM leaders. It supports high-achieving students who demonstrate both academic excellence and a strong commitment to innovation and progress.' . "\n\n" . 'Through full tuition coverage, research support, and mentorship opportunities, the program goes beyond financial aid by preparing scholars for real-world challenges. It nurtures their potential by connecting them with industry professionals and providing platforms for growth, leadership, and discovery.',
                'gpa_requirement'   => 1.50,
                'income_bracket'    => 'Below ₱480,000 annually',
                'slots'             => 75,
                'eligibility'       => "Filipino citizen enrolled in a STEM-related course\n\nMust maintain a GWA of 1.50 throughout the program\n\nMust not have any disciplinary records from previous institution\n\nMust submit a valid scholarship application form and supporting documents\n\nMust demonstrate financial need with income bracket qualification\n\nMust be a full-time student with no other active scholarship",
                'benefits'          => "Full tuition coverage up to ₱30,000 annually\n\nMonthly stipend of ₱3,000\n\nResearch and laboratory allowance of ₱5,000 per year\n\nMentorship from partner institutions and industry professionals\n\nPriority access to internship opportunities\n\nBook and equipment allowance per semester\n\nParticipation in annual scholars' summit and recognition event",
                'requirements'      => "Scholarship Application Form\n\nPSA Birth Certificate\n\nForm 138 or Latest TOR\n\nCertificate of Good Moral Character\n\nITR or Certificate of Non-Filing\n\n2x2 ID Photo (2 copies)\n\nMedical Certificate\n\nBarangay Certificate of Residency",
                'open_date'         => '2025-12-01',
                'deadline'          => '2026-02-28',
                'status'            => 'closed',
                'blind_screening'   => 0,
                'weight_gpa'        => 60,
                'weight_income'     => 40,
                'tags'              => null,
                'ai_match_enabled'  => 1,
                'gcal_event_id'     => null,
                'contact_email'     => 'info@summitedsupport.org.ph',
                'website'           => 'https://www.summitedsupport.org.ph',
                'address'           => 'Unit 8B Zeta Tower, Bridgetowne, Quezon City 1110',
                'benefit_snippet_1' => 'Full tuition coverage up to ₱30,000/yr',
                'benefit_snippet_2' => 'Monthly stipend of ₱3,000',
                'org_logo'          => 'storage/app/logos/summit_educational_support.png',
                'posted_at'         => '2025-11-20 00:00:00',
            ],
            // 4 — Lingap Kabataan Scholarship
            [
                'provider_name'     => 'Bayanihan Community Development Foundation',
                'created_by'        => 28,
                'name'              => 'Lingap Kabataan Scholarship',
                'tagline'           => 'Building Communities, Building Futures',
                'description'       => 'The Lingap Kabataan Scholarship by Bayanihan Community Development Foundation is a community-driven initiative that provides educational support to students from underserved backgrounds. It seeks to ensure that financial limitations do not hinder access to quality education.' . "\n\n" . 'In addition to tuition assistance and stipends, the program promotes holistic development through career guidance and community engagement activities. It empowers scholars to become active contributors to society while pursuing their academic goals.',
                'gpa_requirement'   => 2.00,
                'income_bracket'    => 'Below ₱216,000',
                'slots'             => 40,
                'eligibility'       => "Filipino citizen and resident of the city/municipality for at least 2 years\n\nMust be enrolled in a public school or state university\n\nMust have no failing grades in the prior semester\n\nMust submit a barangay certificate as proof of residency\n\nMust not currently hold any other scholarship\n\nMust be from a household within the qualified income bracket",
                'benefits'          => "Partial tuition assistance up to ₱15,000 annually\n\nAnnual stipend of ₱8,000 released quarterly\n\nSchool supplies allowance at the start of every semester\n\nCommunity service opportunities coordinated by the foundation\n\nCertificate of recognition for academic performance\n\nAccess to free career guidance and counseling sessions",
                'requirements'      => "Barangay Certificate of Indigency\n\nCertificate of Residency (at least 2 years)\n\nLatest Report Card or TOR\n\nCertificate of Good Moral Character\n\nPSA Birth Certificate\n\n2x2 ID Photo (2 copies)\n\nProof of Enrollment\n\nCedula (Community Tax Certificate)",
                'open_date'         => '2025-12-01',
                'deadline'          => '2026-02-28',
                'status'            => 'closed',
                'blind_screening'   => 0,
                'weight_gpa'        => 40,
                'weight_income'     => 60,
                'tags'              => null,
                'ai_match_enabled'  => 1,
                'gcal_event_id'     => null,
                'contact_email'     => 'connect@bayanihanfoundation.org',
                'website'           => 'https://www.bayanihanfoundation.org',
                'address'           => '88 Quezon Avenue, South Triangle, Quezon City 1103',
                'benefit_snippet_1' => 'Partial tuition assistance up to ₱15,000/yr',
                'benefit_snippet_2' => 'Annual stipend of ₱8,000 released quarterly',
                'org_logo'          => 'storage/app/logos/bayanihan_community_dev.png',
                'posted_at'         => '2025-11-22 00:00:00',
            ],
            // 5 — Bukas Palad Scholarship
            [
                'provider_name'     => 'Palad ng Pagbabago Social Foundation',
                'created_by'        => 28,
                'name'              => 'Bukas Palad Scholarship',
                'tagline'           => 'A Helping Hand for Every Filipino Dream',
                'description'       => 'The Bukas Palad Scholarship by Palad ng Pagbabago Social Foundation is a compassionate initiative that extends educational opportunities to students from indigent families. It is built on the belief that every student deserves a chance to succeed regardless of financial circumstances.' . "\n\n" . 'By offering financial support and requiring demonstrated need, the program encourages resilience, responsibility, and perseverance. It serves as a lifeline for students striving to complete their education and build a better future for themselves and their families.',
                'gpa_requirement'   => 1.75,
                'income_bracket'    => 'Below ₱144,000 annually',
                'slots'             => 60,
                'eligibility'       => "Filipino citizen from an indigent or low-income family\n\nMust not be a recipient of any other scholarship\n\nMust have a GWA of 1.75 or higher in the previous semester\n\nMust submit a notarized affidavit of financial need\n\nMust be currently enrolled in a recognized school or university\n\nMust have no disciplinary or administrative cases on record",
                'benefits'          => "Filipino citizen from an indigent or low-income family\n\nMust not be a recipient of any other scholarship\n\nMust have a GWA of 1.75 or higher in the previous semester\n\nMust submit a notarized affidavit of financial need\n\nMust be currently enrolled in a recognized school or university\n\nMust have no disciplinary or administrative cases on record",
                'requirements'      => "Barangay Certificate of Indigency\n\nITR or Certificate of Non-Filing\n\nLatest Report Card or TOR\n\nCertificate of Good Moral Character\n\nPSA Birth Certificate\n\n2x2 ID Photo (2 copies)\n\nProof of Enrollment\n\nAffidavit of Financial Need (notarized)",
                'open_date'         => '2025-12-01',
                'deadline'          => '2026-02-28',
                'status'            => 'closed',
                'blind_screening'   => 0,
                'weight_gpa'        => 50,
                'weight_income'     => 50,
                'tags'              => null,
                'ai_match_enabled'  => 1,
                'gcal_event_id'     => null,
                'contact_email'     => 'apply@paladngpagbabago.org',
                'website'           => 'https://www.paladngpagbabago.org',
                'address'           => '22 A. Mabini St., Brgy. Poblacion, Makati City 1210',
                'benefit_snippet_1' => 'Financial aid for indigent families',
                'benefit_snippet_2' => 'GWA of 1.75+ required to qualify',
                'org_logo'          => 'storage/app/logos/palad_ng_pagbabago.png',
                'posted_at'         => '2025-11-22 00:00:00',
            ],
            // 6 — EmpowerED Academic Scholarship
            [
                'provider_name'     => 'EmpowerED Community Foundation',
                'created_by'        => 28,
                'name'              => 'EmpowerED Academic Scholarship',
                'tagline'           => 'Empowering Families Through Education',
                'description'       => 'The EmpowerED Academic Scholarship by EmpowerED Community Foundation is dedicated to uplifting students from extremely low-income households, particularly those facing unstable family income conditions. It recognizes the importance of education in breaking cycles of poverty.' . "\n\n" . 'Beyond tuition support and stipends, the program extends its impact by providing mentoring, career guidance, and livelihood opportunities for families. It empowers scholars not only academically but also socially and economically.',
                'gpa_requirement'   => 2.00,
                'income_bracket'    => 'Below ₱120,000 annually',
                'slots'             => 30,
                'eligibility'       => "Filipino citizen from a low-income household\n\nParent or guardian must be unemployed or with unstable income\n\nMust have no failing grades in the previous semester\n\nMust submit parent/guardian's employment certificate or affidavit of unemployment\n\nMust not currently hold any other active scholarship\n\nMust be enrolled full-time in a recognized school or university\n\nMust demonstrate willingness to participate in foundation activities",
                'benefits'          => "Tuition subsidy up to ₱12,000 annually\n\nMonthly living allowance of ₱1,500\n\nFree school supplies kit provided every semester\n\nAccess to free livelihood seminars for parents/guardians\n\nCareer counseling and academic mentoring sessions\n\nCertificate of recognition upon completion of each academic year\n\nCommunity engagement and volunteer opportunities",
                'requirements'      => "Barangay Certificate of Indigency\n\nCertificate of Non-Filing or ITR\n\nLatest Report Card or TOR\n\nCertificate of Good Moral Character\n\nPSA Birth Certificate\n\n2x2 ID Photo (2 copies)\n\nProof of Enrollment\n\nParent/Guardian's Employment Certificate or Affidavit of Unemployment",
                'open_date'         => '2025-12-01',
                'deadline'          => '2026-02-28',
                'status'            => 'closed',
                'blind_screening'   => 1,
                'weight_gpa'        => 40,
                'weight_income'     => 60,
                'tags'              => null,
                'ai_match_enabled'  => 1,
                'gcal_event_id'     => null,
                'contact_email'     => 'scholars@empoweredph.org',
                'website'           => 'https://www.empoweredph.org',
                'address'           => 'G/F Cityland Herrera Tower, V.A. Rufino St., Legaspi Village, Makati City 1229',
                'benefit_snippet_1' => 'Tuition subsidy up to ₱12,000/yr',
                'benefit_snippet_2' => 'Monthly living allowance of ₱1,500',
                'org_logo'          => 'storage/app/logos/empowered_community_foundation.png',
                'posted_at'         => '2025-11-25 00:00:00',
            ],
            // 7 — STEM Forward Scholars Program
            [
                'provider_name'     => 'Philippine Science Advancement Initiative',
                'created_by'        => 29,
                'name'              => 'STEM Forward Scholars Program',
                'tagline'           => 'Fueling the Next Generation of Filipino Scientists',
                'description'       => 'The STEM Forward Scholars Program by the Philippine Science Advancement Initiative is a prestigious program designed for top-performing students in science and technology fields. It aims to cultivate future innovators who will contribute to national and global development.' . "\n\n" . 'With comprehensive benefits such as full tuition coverage, research grants, and internships, the program creates an environment where scholars can excel. It also offers mentorship and exposure to industry leaders, shaping well-rounded professionals ready to lead in STEM fields.',
                'gpa_requirement'   => 1.25,
                'income_bracket'    => 'Below ₱300,000 annually',
                'slots'             => 100,
                'eligibility'       => "Filipino citizen enrolled in a science, technology, engineering, or math course\n\nMust submit a recommendation letter from the school principal\n\nMust submit a 500-word essay on why they deserve the scholarship\n\nMust have a GWA of 1.25 or higher with no failing grades\n\nMust not be a recipient of any other scholarship\n\nMust be a full-time student committed to finishing their degree\n\nMust have no disciplinary or administrative cases on record",
                'benefits'          => "Full tuition coverage up to ₱40,000 annually\n\nMonthly stipend of ₱3,500\n\nAccess to research grants and science competitions\n\nMentorship program with industry partners and professionals\n\nPriority access to internship placements in STEM companies\n\nBook and laboratory equipment allowance per semester\n\nAnnual scholars' recognition and awards ceremony",
                'requirements'      => "Scholarship Application Form\n\nPSA Birth Certificate\n\nLatest TOR or Form 138\n\nCertificate of Good Moral Character\n\nITR or Certificate of Non-Filing\n\n2x2 ID Photo (2 copies)\n\nLetter of Recommendation from School Principal\n\nEssay (Why do you deserve this scholarship – 500 words)",
                'open_date'         => '2025-12-01',
                'deadline'          => '2026-03-31',
                'status'            => 'open',
                'blind_screening'   => 0,
                'weight_gpa'        => 70,
                'weight_income'     => 30,
                'tags'              => null,
                'ai_match_enabled'  => 1,
                'gcal_event_id'     => null,
                'contact_email'     => 'stemforward@psai.org.ph',
                'website'           => 'https://www.psai.org.ph',
                'address'           => '3F STEM Forward Building, Gen. Santos Ave., Bicutan, Taguig City 1631',
                'benefit_snippet_1' => 'Full tuition coverage up to ₱40,000/yr',
                'benefit_snippet_2' => 'Monthly stipend of ₱3,500',
                'org_logo'          => 'storage/app/logos/philippine_science_advancement.png',
                'posted_at'         => '2025-11-25 00:00:00',
            ],
            // 8 — Bright Horizons Academic Grant
            [
                'provider_name'     => 'Bright Horizons Development Foundation',
                'created_by'        => 29,
                'name'              => 'Bright Horizons Academic Grant',
                'tagline'           => 'Lighting the Path to Opportunity',
                'description'       => 'The Bright Horizons Academic Grant by Bright Horizons Development Foundation supports students who demonstrate both academic excellence and active community involvement. It emphasizes the importance of balancing education with social responsibility.' . "\n\n" . 'In addition to financial assistance, the program provides health support, training opportunities, and community engagement activities. It aims to develop scholars who are not only knowledgeable but also compassionate and community-oriented leaders.',
                'gpa_requirement'   => 1.75,
                'income_bracket'    => 'Below ₱264,000 annually',
                'slots'             => 35,
                'eligibility'       => "Filipino citizen who is an active member of a community organization or barangay program\n\nMust maintain residency in the community throughout the scholarship period\n\nMust have a GWA of 1.75 or higher in the previous semester\n\nMust submit a medical certificate as part of application requirements\n\nMust not currently hold any other scholarship\n\nMust demonstrate financial need through submitted documents\n\nMust have no disciplinary or administrative cases on record",
                'benefits'          => "Tuition assistance up to ₱22,000 annually\n\nQuarterly stipend of ₱3,000\n\nMedical and health allowance of ₱2,000 per year\n\nAccess to community development programs and training\n\nBook and school supplies allowance per semester\n\nCertificate of recognition for academic and community involvement\n\nParticipation in foundation-led community outreach activities",
                'requirements'      => "Barangay Certificate of Residency\n\nITR or Certificate of Non-Filing\n\nLatest Report Card or TOR\n\nCertificate of Good Moral Character\n\nPSA Birth Certificate\n\n2x2 ID Photo (2 copies)\n\nProof of Enrollment\n\nMedical Certificate",
                'open_date'         => '2025-12-01',
                'deadline'          => '2026-02-28',
                'status'            => 'closed',
                'blind_screening'   => 0,
                'weight_gpa'        => 50,
                'weight_income'     => 50,
                'tags'              => null,
                'ai_match_enabled'  => 1,
                'gcal_event_id'     => null,
                'contact_email'     => 'programs@brighthorizonsph.org',
                'website'           => 'https://www.brighthorizonsph.org',
                'address'           => '55 Lanang Drive, Davao City, Davao del Sur 8000',
                'benefit_snippet_1' => 'Full tuition coverage up to ₱40,000/yr',
                'benefit_snippet_2' => 'Monthly stipend of ₱3,500',
                'org_logo'          => 'storage/app/logos/philippine_science_advancement.png',
                'posted_at'         => '2025-11-25 00:00:00',
            ],
            // 9 — ExcelEdge Merit Scholarship
            [
                'provider_name'     => 'ExcelEdge Academic Foundation',
                'created_by'        => 29,
                'name'              => 'ExcelEdge Merit Scholarship',
                'tagline'           => 'Leaders in Learning, Champions in Life',
                'description'       => 'The ExcelEdge Merit Scholarship by ExcelEdge Academic Foundation recognizes students who embody leadership, initiative, and academic excellence. It is designed for individuals who actively contribute to their communities and organizations.' . "\n\n" . 'Through financial support, leadership training, and networking opportunities, the program nurtures scholars to become confident and capable leaders. It encourages them to use their skills and knowledge to create meaningful impact in their chosen fields.',
                'gpa_requirement'   => 1.50,
                'income_bracket'    => 'Below ₱360,000 annually',
                'slots'             => 25,
                'eligibility'       => "Filipino citizen who demonstrates strong leadership qualities\n\nMust be an active member of a barangay youth council, school organization, or similar group\n\nMust have no disciplinary or administrative records on file\n\nMust have a GWA of 1.50 or higher in the previous semester\n\nMust not currently hold any other scholarship\n\nMust be enrolled full-time in a recognized school or university\n\nMust submit a letter of recommendation from a teacher or community leader",
                'benefits'          => "Tuition fee coverage up to ₱25,000 annually\n\nMonthly stipend of ₱2,000\n\nLeadership training programs and seminar access\n\nShort essay coaching and academic writing workshops\n\nBook and school supplies allowance per semester\n\nCertificate of recognition for leadership and academic excellence\n\nNetworking opportunities with foundation alumni and partners",
                'requirements'      => "Scholarship Application Form\n\nPSA Birth Certificate\n\nLatest TOR or Form 138\n\nCertificate of Good Moral Character\n\nITR or Certificate of Non-Filing\n\n2x2 ID Photo (2 copies)\n\nLetter of Recommendation (from teacher or community leader)\n\nShort Essay (Academic Goals – 300 words)",
                'open_date'         => '2025-12-01',
                'deadline'          => '2026-02-28',
                'status'            => 'closed',
                'blind_screening'   => 0,
                'weight_gpa'        => 60,
                'weight_income'     => 40,
                'tags'              => null,
                'ai_match_enabled'  => 1,
                'gcal_event_id'     => null,
                'contact_email'     => 'merit@exceledgeacademic.org',
                'website'           => 'https://www.exceledgeacademic.org',
                'address'           => '10/F Cebu IT Park, Apas, Cebu City 6000',
                'benefit_snippet_1' => 'Tuition fee coverage up to ₱25,000/yr',
                'benefit_snippet_2' => 'Monthly stipend of ₱2,000',
                'org_logo'          => 'storage/app/logos/exceledge_academic_foundation.png',
                'posted_at'         => '2025-11-27 00:00:00',
            ],
            // 10 — Bayanihan Scholars Grant Program
            [
                'provider_name'     => 'Bayanihan Educational Foundation, Inc.',
                'created_by'        => 30,
                'name'              => 'Bayanihan Scholars Grant Program',
                'tagline'           => 'Empowering Dreams Through Collective Support',
                'description'       => 'The Bayanihan Scholars Grant Program is designed to support academically deserving students from low-income families across the Philippines. This initiative provides financial assistance for tuition, school supplies, and basic educational needs, ensuring that students can focus on their studies without the burden of financial constraints. The program reflects the Filipino spirit of bayanihan by encouraging collective action in uplifting the lives of young learners.' . "\n\n" . 'Beyond financial aid, the program fosters personal growth and social responsibility among its scholars. Recipients are encouraged to participate in community service, leadership activities, and mentorship programs that help them develop both academically and socially. Through this holistic approach, the scholarship aims to produce graduates who are not only successful in their fields but also committed to giving back to their communities.',
                'gpa_requirement'   => 2.00,
                'income_bracket'    => 'Below ₱168,000 annually',
                'slots'             => 55,
                'eligibility'       => "Filipino citizen from a low-income household\n\nMust submit proof of residency and financial need\n\nMust have a GWA of 2.00 or higher in the previous semester\n\nMust not be a recipient of any other active scholarship\n\nMust be enrolled in a recognized school or state university\n\nMust submit a notarized affidavit of financial need\n\nMust have no failing grades in the prior academic term",
                'benefits'          => "Partial tuition assistance up to ₱14,000 annually\n\nQuarterly stipend of ₱2,000\n\nUtility bill subsidy support up to ₱1,500 per year\n\nAccess to free academic counseling and guidance sessions\n\nSchool supplies allowance at the start of every semester\n\nCertificate of recognition upon successful completion of the school year\n\nCommunity engagement opportunities through the foundation",
                'requirements'      => "Barangay Certificate of Indigency\n\nITR or Certificate of Non-Filing\n\nLatest Report Card or TOR\n\nCertificate of Good Moral Character\n\nPSA Birth Certificate\n\n2x2 ID Photo (2 copies)\n\nProof of Enrollment\n\nAffidavit of Financial Need (notarized)\n\nUtility Bill (proof of residence)",
                'open_date'         => '2025-12-01',
                'deadline'          => '2026-03-31',
                'status'            => 'open',
                'blind_screening'   => 0,
                'weight_gpa'        => 50,
                'weight_income'     => 50,
                'tags'              => null,
                'ai_match_enabled'  => 1,
                'gcal_event_id'     => null,
                'contact_email'     => 'scholars@bayanihanfoundation.ph',
                'website'           => 'https://www.bayanihanscholars.ph',
                'address'           => '3rd Floor, Mabuhay Building, 123 Aurora Boulevard, Quezon City, Metro Manila, Philippines',
                'benefit_snippet_1' => 'Partial tuition assistance up to ₱14,000/yr',
                'benefit_snippet_2' => 'Quarterly stipend of ₱2,000',
                'org_logo'          => 'storage/app/logos/bayanihan_educational_foundation.png',
                'posted_at'         => '2025-11-28 00:00:00',
            ],
            // 11 — Unity Scholars Financial Aid Program
            [
                'provider_name'     => 'Unity for Education Foundation PH',
                'created_by'        => 30,
                'name'              => 'Unity Scholars Financial Aid Program',
                'tagline'           => 'Together We Learn, Together We Rise',
                'description'       => 'The Unity Scholars Financial Aid Program by Unity for Education Foundation PH is committed to helping financially challenged students achieve academic success. It provides a strong support system for students striving to complete their college education.' . "\n\n" . 'Beyond financial assistance, the program offers mentoring, tutoring, and community service opportunities. It aims to develop well-rounded individuals who are academically capable and socially responsible.',
                'gpa_requirement'   => 2.00,
                'income_bracket'    => 'Below ₱192,000 annually',
                'slots'             => 20,
                'eligibility'       => "Filipino citizen currently enrolled in any 2 or 4-year college course\n\nMust not be a recipient of any other government or private scholarship\n\nMust have no failing grades in the previous semester\n\nMust be from a household within the qualified income bracket\n\nMust submit a barangay certificate of indigency\n\nMust demonstrate financial need through submitted documents\n\nMust be a full-time student in good academic standing",
                'benefits'          => "Tuition assistance up to ₱16,000 annually\n\nAnnual stipend of ₱7,000 released quarterly\n\nSchool supplies allowance at the start of every semester\n\nAccess to free academic mentoring and tutoring sessions\n\nCertificate of recognition upon completion of each school year\n\nCommunity service opportunities coordinated by the foundation\n\nPriority access to foundation-led career development workshops",
                'requirements'      => "Barangay Certificate of Indigency\n\nITR or Certificate of Non-Filing\n\nLatest Report Card or TOR\n\nCertificate of Good Moral Character\n\nPSA Birth Certificate\n\n2x2 ID Photo (2 copies)\n\nProof of Enrollment\n\nCedula",
                'open_date'         => '2025-12-01',
                'deadline'          => '2026-02-28',
                'status'            => 'closed',
                'blind_screening'   => 0,
                'weight_gpa'        => 50,
                'weight_income'     => 50,
                'tags'              => null,
                'ai_match_enabled'  => 1,
                'gcal_event_id'     => null,
                'contact_email'     => 'financial.aid@unityforeducation.ph',
                'website'           => 'https://www.unityforeducation.ph',
                'address'           => 'Brgy. Tejero, Carmen, Cagayan de Oro City 9000',
                'benefit_snippet_1' => 'Tuition assistance up to ₱16,000/yr',
                'benefit_snippet_2' => 'Annual stipend of ₱7,000 released quarterly',
                'org_logo'          => 'storage/app/logos/unity_for_education_foundation.png',
                'posted_at'         => '2025-11-28 00:00:00',
            ],
            // 12 — LiftED Youth Scholarship Grant
            [
                'provider_name'     => 'LiftED Philippines Foundation',
                'created_by'        => 30,
                'name'              => 'LiftED Youth Scholarship Grant',
                'tagline'           => 'Lifting Families Out of Poverty Through Education',
                'description'       => 'The LiftED Youth Scholarship Grant by LiftED Philippines Foundation is designed to support students from low-income families in overcoming financial and personal challenges. It seeks to empower youth through education and life skills development.' . "\n\n" . 'With financial assistance, career counseling, and skills training, the program prepares scholars for both academic success and real-world responsibilities. It promotes growth, resilience, and long-term empowerment.',
                'gpa_requirement'   => 1.75,
                'income_bracket'    => 'Below ₱132,000 annually',
                'slots'             => 30,
                'eligibility'       => "Filipino citizen from a low-income family\n\nParent or guardian must submit proof of employment or payslip\n\nMust have a GWA of 1.75 or higher in the previous semester\n\nMust not currently hold any other scholarship\n\nMust submit a notarized affidavit of financial need\n\nMust be enrolled full-time in a recognized school or university\n\nMust have no disciplinary or administrative cases on record",
                'benefits'          => "Tuition assistance up to ₱13,000 annually\n\nQuarterly stipend of ₱2,500\n\nNotarized affidavit processing support and guidance\n\nBook and school materials allowance per semester\n\nAccess to free career counseling and life skills sessions\n\nCertificate of recognition upon completion of each academic year\n\nCommunity engagement opportunities through the foundation",
                'requirements'      => "Barangay Certificate of Indigency\n\nITR or Certificate of Non-Filing\n\nLatest Report Card or TOR\n\nCertificate of Good Moral Character\n\nPSA Birth Certificate\n\n2x2 ID Photo (2 copies)\n\nProof of Enrollment\n\nAffidavit of Financial Need (notarized)\n\nParent/Guardian's Payslip or Certificate of Employment",
                'open_date'         => '2025-12-01',
                'deadline'          => '2026-02-28',
                'status'            => 'closed',
                'blind_screening'   => 0,
                'weight_gpa'        => 50,
                'weight_income'     => 50,
                'tags'              => null,
                'ai_match_enabled'  => 1,
                'gcal_event_id'     => null,
                'contact_email'     => 'apply@liftedphilippines.org',
                'website'           => 'https://www.liftedphilippines.org',
                'address'           => '7 Pili Drive, Legarda, Sampaloc, Manila 1008',
                'benefit_snippet_1' => 'Tuition assistance up to ₱13,000/yr',
                'benefit_snippet_2' => 'Quarterly stipend of ₱2,500',
                'org_logo'          => 'storage/app/logos/lifted_philippines_foundation.png',
                'posted_at'         => '2025-11-29 00:00:00',
            ],
            // 13 — Paglaum Scholarship Program
            [
                'provider_name'     => 'Paglaum at Pag-ibig ng Bayan Foundation',
                'created_by'        => 30,
                'name'              => 'Paglaum Scholarship Program',
                'tagline'           => 'Hope and Love for Every Filipino Student',
                'description'       => 'The Paglaum Scholarship Program by Paglaum at Pag-ibig ng Bayan Foundation focuses on supporting students from specific communities who demonstrate both academic potential and good character. It emphasizes holistic well-being alongside education.' . "\n\n" . 'In addition to financial aid, the program offers health-related benefits and community engagement opportunities. It aims to nurture students who are not only academically capable but also socially aware and active.',
                'gpa_requirement'   => 2.25,
                'income_bracket'    => 'Below ₱156,000 annually',
                'slots'             => 65,
                'eligibility'       => "Filipino citizen and resident of the covered barangay or municipality\n\nMust maintain a clean academic and disciplinary record\n\nMust have a GWA of 2.25 or higher in the previous semester\n\nMust not be a recipient of any other scholarship program\n\nMust submit a medical certificate as part of the application\n\nMust demonstrate financial need through submitted documents\n\nMust be enrolled full-time in a recognized school or university",
                'benefits'          => "Tuition assistance up to ₱15,000 annually\n\nMedical and health allowance of ₱3,000 per year\n\nAnnual stipend of ₱6,000 released quarterly\n\nBook and school supplies allowance per semester\n\nAccess to health and wellness programs offered by the foundation\n\nCertificate of recognition for academic performance each school year\n\nParticipation in foundation-organized community and civic activities",
                'requirements'      => "Barangay Certificate of Residency\n\nITR or Certificate of Non-Filing\n\nLatest Report Card or TOR\n\nCertificate of Good Moral Character\n\nPSA Birth Certificate\n\n2x2 ID Photo (2 copies)\n\nProof of Enrollment\n\nMedical Certificate\n\nCedula",
                'open_date'         => '2025-12-01',
                'deadline'          => '2026-03-31',
                'status'            => 'open',
                'blind_screening'   => 0,
                'weight_gpa'        => 50,
                'weight_income'     => 50,
                'tags'              => null,
                'ai_match_enabled'  => 1,
                'gcal_event_id'     => null,
                'contact_email'     => 'paglaum@pagibigngbayan.org.ph',
                'website'           => 'https://www.pagibigngbayan.org.ph',
                'address'           => 'Km. 5, Mati City, Davao Oriental 8200',
                'benefit_snippet_1' => 'Tuition assistance up to ₱15,000/yr',
                'benefit_snippet_2' => 'Medical and health allowance of ₱3,000/yr',
                'org_logo'          => 'storage/app/logos/paglaum_at_pagibig_ng_bayan.png',
                'posted_at'         => '2025-11-29 00:00:00',
            ],
            // 14 — Catalyst Scholars Program
            [
                'provider_name'     => 'Catalyst for Education Foundation',
                'created_by'        => 31,
                'name'              => 'Catalyst Scholars Program',
                'tagline'           => 'Catalyzing Change Through Accessible Education',
                'description'       => 'The Catalyst Scholars Program by Catalyst for Education Foundation is a transformative initiative that supports students with strong academic potential and leadership qualities. It is designed to prepare scholars for meaningful contributions in their chosen careers.' . "\n\n" . 'Through full tuition support, stipends, and professional development programs, the scholarship fosters both academic and personal growth. It also provides networking and mentorship opportunities that open doors for future success.',
                'gpa_requirement'   => 1.75,
                'income_bracket'    => 'Below ₱228,000 annually',
                'slots'             => 90,
                'eligibility'       => "Filipino citizen currently enrolled in a recognized college or university\n\nMust submit a letter of recommendation from the school\n\nMust maintain a GWA of 1.75 or higher throughout the scholarship period\n\nMust not be a recipient of any other scholarship\n\nMust have no failing grades in the previous academic term\n\nMust be a full-time student in good academic standing\n\nMust have no disciplinary or administrative cases on record",
                'benefits'          => "Full tuition coverage up to ₱30,000 annually\n\nQuarterly stipend of ₱3,000\n\nBook and school supplies allowance per semester\n\nAccess to academic mentoring and professional development sessions\n\nNetworking opportunities with foundation partners and alumni\n\nAnnual scholars' recognition and awards ceremony\n\nPriority consideration for internship placements at partner organizations",
                'requirements'      => "Scholarship Application Form\n\nPSA Birth Certificate\n\nLatest TOR or Form 138\n\nCertificate of Good Moral Character\n\nITR or Certificate of Non-Filing\n\n2x2 ID Photo (2 copies)\n\nProof of Enrollment\n\nLetter of Recommendation from School",
                'open_date'         => '2025-12-01',
                'deadline'          => '2026-02-28',
                'status'            => 'closed',
                'blind_screening'   => 0,
                'weight_gpa'        => 60,
                'weight_income'     => 40,
                'tags'              => null,
                'ai_match_enabled'  => 1,
                'gcal_event_id'     => null,
                'contact_email'     => 'scholars@catalysteducation.ph',
                'website'           => 'https://www.catalysteducation.ph',
                'address'           => '2F Regus Bldg, Ayala Ave., Salcedo Village, Makati City 1227',
                'benefit_snippet_1' => 'Full tuition coverage up to ₱30,000/yr',
                'benefit_snippet_2' => 'Quarterly stipend of ₱3,000',
                'org_logo'          => 'storage/app/logos/catalyst_for_education_foundation.png',
                'posted_at'         => '2025-11-30 00:00:00',
            ],
            // 15 — AccessPlus Financial Aid Program
            [
                'provider_name'     => 'AccessPlus Opportunities Foundation',
                'created_by'        => 31,
                'name'              => 'AccessPlus Financial Aid Program',
                'tagline'           => 'More Access, More Opportunities, More Futures',
                'description'       => 'The AccessPlus Financial Aid Program by AccessPlus Opportunities Foundation supports students from indigent households by providing financial assistance and essential resources. It aims to remove barriers that prevent students from completing their education.' . "\n\n" . 'In addition to tuition support and stipends, the program offers financial literacy training and life skills workshops. It empowers scholars to manage their resources effectively and build sustainable futures.',
                'gpa_requirement'   => 2.00,
                'income_bracket'    => 'Below ₱204,000 annually',
                'slots'             => 70,
                'eligibility'       => "Filipino citizen from an indigent household\n\nMust submit proof of financial need including utility bills\n\nMust have a GWA of 2.00 or higher in the previous semester\n\nMust not currently hold any other scholarship\n\nMust submit a notarized affidavit of financial need\n\nMust be enrolled full-time in a recognized school or university\n\nMust have no disciplinary or administrative cases on record",
                'benefits'          => "Tuition assistance up to ₱17,000 annually\n\nQuarterly stipend of ₱2,500\n\nUtility bill subsidy support up to ₱2,000 per year\n\nAffidavit support and legal document assistance\n\nBook and school supplies allowance per semester\n\nCertificate of recognition upon completion of each academic year\n\nAccess to foundation-led financial literacy and life skills workshops",
                'requirements'      => "Barangay Certificate of Indigency\n\nITR or Certificate of Non-Filing\n\nLatest Report Card or TOR\n\nCertificate of Good Moral Character\n\nPSA Birth Certificate\n\n2x2 ID Photo (2 copies)\n\nProof of Enrollment\n\nAffidavit of Financial Need (notarized)\n\nUtility Bill (proof of residence)",
                'open_date'         => '2025-12-01',
                'deadline'          => '2026-02-28',
                'status'            => 'closed',
                'blind_screening'   => 0,
                'weight_gpa'        => 50,
                'weight_income'     => 50,
                'tags'              => null,
                'ai_match_enabled'  => 1,
                'gcal_event_id'     => null,
                'contact_email'     => 'info@accessplusph.org',
                'website'           => 'https://www.accessplusph.org',
                'address'           => '18 Gen. Luna St., Iloilo City, Iloilo 5000',
                'benefit_snippet_1' => 'Tuition assistance up to ₱17,000/yr',
                'benefit_snippet_2' => 'Quarterly stipend of ₱2,500',
                'org_logo'          => 'storage/app/logos/accessplus_opportunities_foundation.png',
                'posted_at'         => '2025-11-30 00:00:00',
            ],
            // 16 — CHED Merit Scholarship Program (CMSP)
            [
                'provider_name'     => 'CHED Scholarship',
                'created_by'        => 31,
                'name'              => 'CHED Merit Scholarship Program (CMSP)',
                'tagline'           => 'Enabling Filipinos to Achieve Quality Higher Education',
                'description'       => 'The CHED Merit Scholarship Program is a government-funded initiative that supports academically outstanding Filipino students in pursuing higher education. It aims to make quality education accessible to deserving individuals across the country.' . "\n\n" . 'By covering tuition, stipends, and academic allowances, the program ensures that scholars can focus on their studies without financial strain. It plays a vital role in developing future professionals who will contribute to national progress.',
                'gpa_requirement'   => 1.08,
                'income_bracket'    => 'Below ₱500,000 annually',
                'slots'             => 2779,
                'eligibility'       => "Filipino Citizen\n\nSenior High school graduate with a minimum general weighted average (GWA) of 93% or its equivalent\n\nCombined annual gross income of parents or legal guardian should not exceed Five Hundred Thousand Pesos (PhP500,000.00)",
                'benefits'          => "This scholarship program shall cover tuition and other school fees (TOSF), stipend which shall be released directly to the scholars or through HEIs, and book connectivity allowance per semester of a given academic year until the completion of the degree program.",
                'requirements'      => "Accomplished Online Application Form\n\nCopy of Birth certificate issued by PSA\n\nCertified true copy of Form 138 duly signed by the registrar\n\nLatest Income Tax Return (ITR) of parents or guardian\n\nCertificate of Tax Exemption/Non-Filer issued by the BIR",
                'open_date'         => '2025-12-01',
                'deadline'          => '2026-03-31',
                'status'            => 'open',
                'blind_screening'   => 0,
                'weight_gpa'        => 70,
                'weight_income'     => 30,
                'tags'              => null,
                'ai_match_enabled'  => 1,
                'gcal_event_id'     => null,
                'contact_email'     => 'cmsp@ched.gov.ph',
                'website'           => 'https://www.ched.gov.ph',
                'address'           => 'HEDC Building, C.P. Garcia Ave., U.P. Campus, Diliman, Quezon City 1101',
                'benefit_snippet_1' => 'Full tuition and other school fees covered',
                'benefit_snippet_2' => 'Stipend released directly to scholars per semester',
                'org_logo'          => 'storage/app/logos/ched.png',
                'posted_at'         => '2025-12-01 00:00:00',
            ],
            // 17 — Charity First Foundation, Inc.
            [
                'provider_name'     => 'Charity First Foundation, Inc.',
                'created_by'        => 31,
                'name'              => 'Charity First Foundation, Inc.',
                'tagline'           => 'Helping People, Help Themselves',
                'description'       => 'The Charity First Foundation Scholarship provides comprehensive support to students enrolled in partner universities, focusing on both academic and personal development. It is designed for students who demonstrate dedication and commitment to their education.' . "\n\n" . 'Beyond financial aid, the program offers housing, allowances, and life skills training. It requires active participation in foundation activities, fostering discipline, responsibility, and a strong sense of community.',
                'gpa_requirement'   => 2.25,
                'income_bracket'    => null,
                'slots'             => 0,
                'eligibility'       => "Must be admitted or enrolled in Charity First Partner Universities\n\nMust be a 1ST and 2ND YEAR COLLEGE STUDENT FOR AY 2025-2026\n\nMedicine, Nursing, Law Courses, Interior Design, Tourism and HRM Courses are NOT ACCEPTED\n\nMUST NOT BE A RECIPIENT OF OTHER SCHOLARSHIP PROGRAM (PARTIAL/FULL)\n\nMUST be DEDICATED to attend Charity First Activities every 1st Sunday of the Month",
                'benefits'          => "Transportation and Meal Allowance\n\nDorm Fee and Allowance\n\nBooks, Uniform Allowance\n\nDesktop and Internet Allowance\n\nLife Skills and Motivational Seminar",
                'requirements'      => "Accomplished Charity First Application Form\n\nComplete Grades (SHS and 1st Year 1st Sem Grades)\n\nLatest University/School Registration Form\n\nAutobiography or Talambuhay\n\nPSA Birth Certificate, School and Government ID's, 2x2 ID Picture and Certificate of Indigency",
                'open_date'         => '2025-12-01',
                'deadline'          => '2026-02-28',
                'status'            => 'closed',
                'blind_screening'   => 0,
                'weight_gpa'        => 50,
                'weight_income'     => 50,
                'tags'              => null,
                'ai_match_enabled'  => 1,
                'gcal_event_id'     => null,
                'contact_email'     => 'info@charityfirst.ph',
                'website'           => 'https://www.charityfirst.ph',
                'address'           => 'Room 207-208 RS Building #906 Quezon Avenue Dr. Garcia, Quezon City Metro Manila Philippines',
                'benefit_snippet_1' => 'Transportation and meal allowance provided',
                'benefit_snippet_2' => 'Dorm fee and book/uniform allowance included',
                'org_logo'          => 'storage/app/logos/charity_first_foundation.png',
                'posted_at'         => '2025-12-01 00:00:00',
            ],
            // 18 — Ayala Foundation Scholarship
            [
                'provider_name'     => 'Ayala Foundation',
                'created_by'        => 31,
                'name'              => 'Ayala Foundation Scholarship',
                'tagline'           => 'We envision communities where people are productive, creative, self-reliant, and proud to be Filipino.',
                'description'       => 'The Ayala Foundation Scholarship is a transformative program that empowers female students in public universities to pursue their educational goals. It promotes leadership, integrity, and community involvement among its scholars.' . "\n\n" . 'Through financial support and development opportunities, the program encourages women to become agents of change. It aims to create a generation of empowered female leaders who will contribute meaningfully to society.',
                'gpa_requirement'   => 1.25,
                'income_bracket'    => null,
                'slots'             => 0,
                'eligibility'       => "Must be a female Filipino student\n\nIncoming first-year, second-year, or third-year college students for SY 25-26\n\nWill enroll in a public or state university/college for SY 25-26\n\nMust not have any existing scholarship\n\nA general weight average (GWA) of at least 85% with no failing grades\n\nDemonstrate financial need\n\nHave no disciplinary or administrative cases",
                'benefits'          => "Each grantee is entitled to receive PHP 40,000 annually, which is renewable as long as she maintains her good academic performance.\n\nScholars have the opportunity to continue their higher education courses without financial burden.",
                'requirements'      => "Duly completed scholarship application form\n\nCertification from the school registrar or Certificate of Registration/Enrollment\n\nThe latest copy of the report card with attendance\n\nParents' or guardians' most recent Income Tax Return (ITR)\n\nLatest Copy of Electric Bill",
                'open_date'         => '2025-12-01',
                'deadline'          => '2026-02-28',
                'status'            => 'closed',
                'blind_screening'   => 0,
                'weight_gpa'        => 60,
                'weight_income'     => 40,
                'tags'              => null,
                'ai_match_enabled'  => 1,
                'gcal_event_id'     => null,
                'contact_email'     => 'ugoadmin@ayalafoundation.org',
                'website'           => 'https://donate.ayalafoundation.org',
                'address'           => '4F Makati Stock Exchange Building, 6767 Ayala Triangle, Ayala Avenue, Makati City 1229',
                'benefit_snippet_1' => '₱40,000 annual grant renewable each year',
                'benefit_snippet_2' => 'For female students in public universities only',
                'org_logo'          => 'storage/app/logos/ayala_foundation.png',
                'posted_at'         => '2025-12-01 00:00:00',
            ],
            // 19 — Panasonic Scholarship
            [
                'provider_name'     => 'Panasonic Holdings Corporation',
                'created_by'        => 31,
                'name'              => 'Panasonic Scholarship',
                'tagline'           => 'Unleash your potential and let education light up your brightest future!',
                'description'       => 'The Panasonic Scholarship supports college students nearing graduation by providing financial assistance and monthly allowances. It aims to help scholars successfully complete their degrees and transition into professional careers.' . "\n\n" . 'By easing financial pressures during critical academic years, the program enables students to focus on their studies and career preparation. It serves as a stepping stone toward achieving long-term professional goals.',
                'gpa_requirement'   => 2.00,
                'income_bracket'    => null,
                'slots'             => 0,
                'eligibility'       => "Must be a Filipino citizen\n\nMust be a full-time student enrolled in a state college or university\n\nMust be a college student\n\nMust be graduating within the next two years",
                'benefits'          => "Fixed Monthly Allowance provided to selected candidates.",
                'requirements'      => "Updated Curriculum Vitae (CV)\n\nCertified True Copy of Grades or Transcript of Records\n\nMust have a General Weighted Average (GWA) of at least 2.00\n\nRecommendation Letter from the Dean\n\nOne (1) 2x2 photo\n\nPhotocopy of School ID",
                'open_date'         => '2025-12-01',
                'deadline'          => '2026-03-31',
                'status'            => 'open',
                'blind_screening'   => 0,
                'weight_gpa'        => 70,
                'weight_income'     => 30,
                'tags'              => null,
                'ai_match_enabled'  => 1,
                'gcal_event_id'     => null,
                'contact_email'     => 'panasoniccsr@ph.panasonic.com',
                'website'           => 'https://www.panasonic.com/ph',
                'address'           => 'Panasonic Scholarship Office- Philippines HR- Training Citizenship, Int PR PMPC-Taytay Compound, Ortigas Avenue Ext., Taytay, Rizal 1920',
                'benefit_snippet_1' => 'Fixed monthly allowance for graduating students',
                'benefit_snippet_2' => 'For students graduating within the next 2 years',
                'org_logo'          => 'storage/app/logos/panasonic_holdings.png',
                'posted_at'         => '2025-12-01 00:00:00',
            ],
            // 20 — Security Bank Regalo Mo Kinabukasan Ko Scholarship
            [
                'provider_name'     => 'Security Bank Foundation, Inc.',
                'created_by'        => 31,
                'name'              => 'Security Bank Regalo Mo Kinabukasan Ko Scholarship',
                'tagline'           => 'Scholars for Better Communities',
                'description'       => 'The Security Bank "Regalo Mo, Kinabukasan Ko" Scholarship is a program that supports the education of students connected to Security Bank personnel. It reflects the organization\'s commitment to investing in education and community development.' . "\n\n" . 'The program provides financial assistance, stipends, and opportunities for internships and learning sessions. It helps scholars pursue their chosen paths while preparing them for future careers through exposure and experience.',
                'gpa_requirement'   => 2.00,
                'income_bracket'    => null,
                'slots'             => 0,
                'eligibility'       => "Agency personnel must be assigned in Security Bank for at least 1 year with a good employment record\n\nChildren of agency personnel or agency personnel themselves are eligible\n\nStudents must have a latest General Weighted Average (GWA) of at least 80% or its equivalent\n\nApplicants should not hold any other existing scholarship except for discounts provided by schools",
                'benefits'          => "Financial Assistance per academic year: Elementary — ₱5,000, Junior High School — ₱7,000, Senior High School — ₱10,000, College — ₱30,000\n\nStipend released quarterly\n\nOpportunities for internship\n\nInvolvement in corporate social responsibility (CSR) activities",
                'requirements'      => "Duly accomplished Online Application Form\n\nLatest Report Card with Final General Weighted Average\n\nBirth Certificate of Scholar\n\nEndorsement letter signed by Security Bank Group\n\nEndorsement letter from the Agency\n\nPortrait Photo of the Scholar\n\nCopy of Agency Personnel ID",
                'open_date'         => '2025-12-01',
                'deadline'          => '2026-02-28',
                'status'            => 'closed',
                'blind_screening'   => 0,
                'weight_gpa'        => 50,
                'weight_income'     => 50,
                'tags'              => null,
                'ai_match_enabled'  => 1,
                'gcal_event_id'     => null,
                'contact_email'     => 'sbfoundation@securitybank.com.ph',
                'website'           => 'https://www.securitybank.com/foundation/external-scholarship-program',
                'address'           => 'Security Bank Head Office, 6776 Ayala Ave E, Makati (Security Bank Foundation, Inc.)',
                'benefit_snippet_1' => 'Financial assistance up to ₱30,000/yr for college',
                'benefit_snippet_2' => 'Quarterly stipend of ₱30,000 for college scholars',
                'org_logo'          => 'storage/app/logos/security_bank_foundation.png',
                'posted_at'         => '2025-12-01 00:00:00',
            ],
            // 21 — Bagong Alab Scholars Fund
            [
                'provider_name'     => 'Bagong Alab Youth Foundation',
                'created_by'        => 32,
                'name'              => 'Bagong Alab Scholars Fund',
                'tagline'           => 'Igniting the Fire of Filipino Excellence',
                'description'       => 'The Bagong Alab Scholars Fund supports incoming first-year college students who graduated Senior High School with distinction. Designed for high-achieving SHS graduates transitioning into college, it eases the financial burden of the critical first year. Beyond tuition aid and stipends, scholars receive mentorship and career orientation to help them navigate college life with confidence and purpose.',
                'gpa_requirement'   => 92.00,
                'income_bracket'    => '≤ ₱300,000/yr',
                'slots'             => 80,
                'eligibility'       => "Filipino SHS graduate with final GPA of 92% or above\n\nMust be enrolling in a recognized college or university for the first time\n\nMust not be a recipient of any other scholarship\n\nMust have no failing grades in any SHS subject\n\nMust demonstrate financial need through submitted documents\n\nMust be a full-time student",
                'benefits'          => "Full tuition assistance up to ₱25,000 for first year\n\nMonthly stipend of ₱2,500\n\nBook and school supplies allowance\n\nMentorship and college orientation program\n\nCertificate of recognition upon completion of first year",
                'requirements'      => "PSA Birth Certificate\n\nSHS Form 138 or Report Card with final GPA\n\nCertificate of Good Moral Character\n\nBarangay Certificate of Indigency\n\nProof of Enrollment or Acceptance Letter\n\n2x2 ID Photo (2 copies)\n\nITR or Certificate of Non-Filing",
                'open_date'         => '2026-03-01',
                'deadline'          => '2026-06-15',
                'status'            => 'open',
                'blind_screening'   => 0,
                'weight_gpa'        => 60,
                'weight_income'     => 40,
                'tags'              => null,
                'ai_match_enabled'  => 1,
                'gcal_event_id'     => null,
                'contact_email'     => 'scholars@bagonalab.org.ph',
                'website'           => 'https://www.bagonalab.org.ph',
                'address'           => '18 Kalayaan Ave., Diliman, Quezon City 1101',
                'benefit_snippet_1' => 'Full tuition assistance up to ₱25,000 for 1st year',
                'benefit_snippet_2' => 'Monthly stipend of ₱2,500',
                'org_logo'          => 'storage/app/logos/bagong_alab_youth_foundation.png',
                'posted_at'         => '2026-03-01 00:00:00',
            ],
            // 22 — Sindak ng Pag-asa Scholarship
            [
                'provider_name'     => 'Sindak Foundation PH',
                'created_by'        => 32,
                'name'              => 'Sindak ng Pag-asa Scholarship',
                'tagline'           => 'From Hope to Achievement, One Scholar at a Time',
                'description'       => 'The Sindak ng Pag-asa Scholarship is committed to giving deserving SHS graduates a strong college start. It targets students from low-income households who have demonstrated academic perseverance throughout their senior high school years. The program provides financial support alongside personal development sessions, ensuring scholars are equipped not just financially but emotionally and academically for the demands of college.',
                'gpa_requirement'   => 88.00,
                'income_bracket'    => '≤ ₱240,000/yr',
                'slots'             => 60,
                'eligibility'       => "Filipino SHS graduate with final GPA of 88% or above\n\nMust come from a household within the qualified income bracket\n\nMust not be a recipient of any other scholarship\n\nMust submit a notarized affidavit of financial need\n\nMust be enrolling as a first-year college student\n\nMust have no disciplinary records from SHS",
                'benefits'          => "Tuition assistance up to ₱18,000 for first year\n\nMonthly stipend of ₱2,000\n\nPersonal development and wellness sessions\n\nBook allowance per semester\n\nCertificate of scholarship upon completion",
                'requirements'      => "PSA Birth Certificate\n\nSHS Form 138 or Report Card with final GPA\n\nCertificate of Good Moral Character\n\nBarangay Certificate of Indigency\n\nAffidavit of Financial Need (notarized)\n\nProof of Enrollment or Acceptance Letter\n\n2x2 ID Photo (2 copies)",
                'open_date'         => '2026-03-01',
                'deadline'          => '2026-06-15',
                'status'            => 'open',
                'blind_screening'   => 1,
                'weight_gpa'        => 50,
                'weight_income'     => 50,
                'tags'              => null,
                'ai_match_enabled'  => 1,
                'gcal_event_id'     => null,
                'contact_email'     => 'info@sindakfoundation.ph',
                'website'           => 'https://www.sindakfoundation.ph',
                'address'           => '45 Rizal St., San Juan, Metro Manila 1500',
                'benefit_snippet_1' => 'Tuition assistance up to ₱18,000 for 1st year',
                'benefit_snippet_2' => 'Monthly stipend of ₱2,000',
                'org_logo'          => 'storage/app/logos/sindak_foundation_ph.png',
                'posted_at'         => '2026-03-01 00:00:00',
            ],
            // 23 — Talino at Puso Grant
            [
                'provider_name'     => 'Talino at Puso Foundation',
                'created_by'        => 32,
                'name'              => 'Talino at Puso Grant',
                'tagline'           => 'Heart and Mind in Every Filipino Dream',
                'description'       => 'The Talino at Puso Grant by Talino at Puso Foundation recognizes SHS graduates who excel both academically and in character. It values the whole student — intellect, values, and community involvement — and provides comprehensive support for their first year in college. Scholars are connected with mentors and peers who share the same commitment to excellence and service.',
                'gpa_requirement'   => 90.00,
                'income_bracket'    => '≤ ₱360,000/yr',
                'slots'             => 50,
                'eligibility'       => "Filipino SHS graduate with final GPA of 90% or above\n\nMust demonstrate good moral character certified by SHS principal\n\nMust be an active member of a school or community organization\n\nMust not be a recipient of any other scholarship\n\nMust be enrolling full-time in a recognized college or university\n\nMust have no disciplinary or administrative cases on record",
                'benefits'          => "Tuition assistance up to ₱20,000 for first year\n\nMonthly stipend of ₱2,500\n\nAccess to mentoring and peer support network\n\nBook and school supplies allowance\n\nCertificate of recognition for academic and character excellence",
                'requirements'      => "PSA Birth Certificate\n\nSHS Form 138 or Report Card with final GPA\n\nCertificate of Good Moral Character\n\nBarangay Certificate of Residency\n\nProof of community or organization membership\n\nProof of Enrollment or Acceptance Letter\n\n2x2 ID Photo (2 copies)",
                'open_date'         => '2026-03-15',
                'deadline'          => '2026-06-30',
                'status'            => 'open',
                'blind_screening'   => 0,
                'weight_gpa'        => 55,
                'weight_income'     => 45,
                'tags'              => null,
                'ai_match_enabled'  => 1,
                'gcal_event_id'     => null,
                'contact_email'     => 'grants@talinoatpuso.org.ph',
                'website'           => 'https://www.talinoatpuso.org.ph',
                'address'           => '3F Puno Building, Ortigas Center, Pasig City 1605',
                'benefit_snippet_1' => 'Tuition assistance up to ₱20,000 for 1st year',
                'benefit_snippet_2' => 'Monthly stipend of ₱2,500',
                'org_logo'          => 'storage/app/logos/talino_at_puso_foundation.png',
                'posted_at'         => '2026-03-15 00:00:00',
            ],
            // 24 — Lakbay Dunong Scholarship
            [
                'provider_name'     => 'Lakbay Dunong Inc.',
                'created_by'        => 32,
                'name'              => 'Lakbay Dunong Scholarship',
                'tagline'           => 'Every Journey to Knowledge Deserves Support',
                'description'       => 'The Lakbay Dunong Scholarship supports incoming college students who come from remote or underserved areas. Recognizing that geography and poverty should never be barriers to education, the program covers essential academic expenses and provides a monthly allowance to help scholars sustain themselves as they begin their college journey far from home.',
                'gpa_requirement'   => 85.00,
                'income_bracket'    => '≤ ₱180,000/yr',
                'slots'             => 70,
                'eligibility'       => "Filipino SHS graduate with final GPA of 85% or above\n\nMust be from a remote, rural, or underserved area\n\nMust come from a household within the qualified income bracket\n\nMust not be a recipient of any other scholarship\n\nMust submit proof of residence from barangay\n\nMust be enrolling as a first-year college student",
                'benefits'          => "Tuition assistance up to ₱16,000 for first year\n\nMonthly living allowance of ₱3,000\n\nTransportation subsidy of ₱1,500/semester\n\nBook and school supplies allowance\n\nBarangay-coordinated support network access",
                'requirements'      => "PSA Birth Certificate\n\nSHS Form 138 or Report Card with final GPA\n\nCertificate of Good Moral Character\n\nBarangay Certificate of Indigency\n\nProof of residence from remote/rural area\n\nProof of Enrollment or Acceptance Letter\n\n2x2 ID Photo (2 copies)\n\nITR or Certificate of Non-Filing",
                'open_date'         => '2026-03-15',
                'deadline'          => '2026-06-30',
                'status'            => 'open',
                'blind_screening'   => 1,
                'weight_gpa'        => 40,
                'weight_income'     => 60,
                'tags'              => null,
                'ai_match_enabled'  => 1,
                'gcal_event_id'     => null,
                'contact_email'     => 'apply@lakbaydunong.org.ph',
                'website'           => 'https://www.lakbaydunong.org.ph',
                'address'           => '77 Bonifacio St., Lipa City, Batangas 4217',
                'benefit_snippet_1' => 'Tuition assistance up to ₱16,000 for 1st year',
                'benefit_snippet_2' => 'Monthly living allowance of ₱3,000',
                'org_logo'          => 'storage/app/logos/lakbay_dunong_inc.png',
                'posted_at'         => '2026-03-15 00:00:00',
            ],
            // 25 — Haligi ng Bayan Academic Award
            [
                'provider_name'     => 'Haligi ng Bayan Foundation',
                'created_by'        => 32,
                'name'              => 'Haligi ng Bayan Academic Award',
                'tagline'           => 'Pillars of the Nation Start in the Classroom',
                'description'       => 'The Haligi ng Bayan Academic Award is a prestigious scholarship for top-performing SHS graduates who aspire to become pillars of Filipino society. It supports students with exceptional academic records and a demonstrated commitment to their communities. The program pairs financial assistance with leadership development activities designed to shape future professionals and community leaders.',
                'gpa_requirement'   => 93.00,
                'income_bracket'    => '≤ ₱420,000/yr',
                'slots'             => 40,
                'eligibility'       => "Filipino SHS graduate with final GPA of 93% or above\n\nMust have been a student leader or active organization member in SHS\n\nMust not be a recipient of any other scholarship\n\nMust submit a recommendation letter from SHS principal\n\nMust demonstrate financial need\n\nMust be enrolling full-time in a recognized college or university",
                'benefits'          => "Full tuition coverage up to ₱35,000 for first year\n\nMonthly stipend of ₱3,000\n\nLeadership development program and seminars\n\nBook and laboratory allowance per semester\n\nAnnual scholars' recognition and awards ceremony",
                'requirements'      => "PSA Birth Certificate\n\nSHS Form 138 or Report Card with final GPA\n\nCertificate of Good Moral Character\n\nLetter of Recommendation from SHS Principal\n\nProof of student leadership or organization membership\n\nProof of Enrollment or Acceptance Letter\n\n2x2 ID Photo (2 copies)",
                'open_date'         => '2026-04-01',
                'deadline'          => '2026-06-30',
                'status'            => 'open',
                'blind_screening'   => 0,
                'weight_gpa'        => 70,
                'weight_income'     => 30,
                'tags'              => null,
                'ai_match_enabled'  => 1,
                'gcal_event_id'     => null,
                'contact_email'     => 'award@haliginbayan.org.ph',
                'website'           => 'https://www.haliginbayan.org.ph',
                'address'           => '22 MacArthur Hwy., Malolos, Bulacan 3000',
                'benefit_snippet_1' => 'Full tuition coverage up to ₱35,000 for 1st year',
                'benefit_snippet_2' => 'Monthly stipend of ₱3,000',
                'org_logo'          => 'storage/app/logos/haligi_ng_bayan_foundation.png',
                'posted_at'         => '2026-04-01 00:00:00',
            ],
        ];

        foreach ($scholarships as $scholarship) {
            Scholarship::create($scholarship);
        }
    }
}
